### ISSUE TITLE
Unable to retrieve results for a valid parkrunner

### ISSUE THREAD

**Issue by rokesby** [jansen88/parkrun-results#15]
Steps to reproduce
- Log into Parkrunner
- Enter 191748 for Runner A191748
- Hit the Submit button
- Results are shown
- 
<img width="1058" alt="Screenshot 2024-05-20 at 16 21 16" src="https://github.com/jansen88/parkrun-results/assets/63777177/6863418c-1af3-4d3b-b21c-f1a4b651e42a">

- Second attempt
- Enter 620924 for Runner https://www.parkrun.org.uk/valentines/parkrunner/620924/
- Hit the submit button
- Error ' No parkrunner profile found for this parkrunner ID'
<img width="423" alt="Screenshot 2024-05-20 at 16 21 31" src="https://github.com/jansen88/parkrun-results/assets/63777177/862a1e02-4f52-427d-896e-28b429b1fc86">

**Comment by jansen88** [comment]
Thanks for raising @rokesby , and documenting reproducible example.

This should be resolved now - please let me know if you're still running issues :)
![image](https://github.com/jansen88/parkrun-results/assets/94953297/ccd67ef3-8584-4930-bd96-4727b7466d9b)

**Comment by rokesby** [comment]
Dear Jansen88, thank you so much for fixing this in rapid time! I did a fetch and tested in Google Chrome and it works great. I'm interested in learning more and contributing to your project. What's the best means of contacting you (assuming you're interested). Thanks again!
